### ISSUE TITLE
Regenerate response and editing message doesn't count

### ISSUE THREAD

**Issue by iNotacat** [ShaneOH/ChatGPT-4-Message-Limit-Tracker#1]
As the title says, 'regenerating response' and 'editing message' doesn't change the message counter. Only new message makes a change in the number of remaining messages with this extension.

**Comment by ShaneOH** [comment]
Hey @iNotacat , good catch! I just pushed the update to address this, and submitted it for review on the Chrome Store. I'll close this issue once it's published -- thanks!

**Comment by ShaneOH** [comment]
This fix should now be published in the Chrome Web Store under version 1.1!
