### ISSUE TITLE
ChatGPT got message limit increase

### ISSUE THREAD

**Issue by iNotacat** [ShaneOH/ChatGPT-4-Message-Limit-Tracker#2]
Hello again,

ChatGPT's message limit increased from 25 to 50 messages. I think it broke the extension.

![gpt message limit](https://github.com/ShaneOH/ChatGPT-4-Message-Limit-Tracker/assets/74687727/15eef965-edd3-4dd6-940f-ad0c3dec15b0)

**Comment by ShaneOH** [comment]
Hey thanks for the ticket! Yeah I'm seeing some funky behavior on my end too now. I'll try to fix it soon when I get the time.

**Comment by ShaneOH** [comment]
@iNotacat Just submitted the fix for review, I'll close this issue once version 1.2 goes live.

**Comment by ShaneOH** [comment]
This fix is now published live as version 1.2!
